### ISSUE TITLE
Missing pandas.to_numeric

### ISSUE THREAD

**Issue by wwuck** [predictive-analytics-lab/data-science-types#108]
The pandas stubs are missing [pandas.to_numeric](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html).

I would like to do a PR but I'm not really sure where to start or how to write proper type hints for this, as I've only just started learning about python typing for the last few days.  Any help would be much appreciated.

**Comment by thomkeh** [comment]
basically:
- look at the documentation of the function
- if that doesn’t help, try it out with a few types and see what works

also, it's very good to have read all of the mypy docs: https://mypy.readthedocs.io/en/stable/builtin_types.html

In your case, for example, the documentation says about the first argument:
> arg: scalar, list, tuple, 1-d array, or Series
so, the type will probably be something like
```
Union[int, float, List, Tuple, np.ndarray, pd.Series]
```

**Comment by wwuck** [comment]
Thanks for that.  I did get a bit stuck on trying to figure out the type for `scalar` as I couldn't see where it was documented on the pandas docs.

**Comment by wwuck** [comment]
@thomkeh  Anything else that needs doing before a new release?

**Comment by thomkeh** [comment]
@wwuck I created a release

I try not to make a release for every commit as that would be a bit silly, but if you want a new release, I can always create one.

**Comment by wwuck** [comment]
Thanks @thomkeh !
