### ISSUE TITLE
Error when typing Numpy arrays within NamedTuples

### ISSUE THREAD

**Issue by adamlichtl** [predictive-analytics-lab/data-science-types#111]
data-science-types==0.2.12
mypy==0.770
typing==3.6.4

Code to reproduce:
```python
import numpy as np
from typing import List, NamedTuple

class Ok(NamedTuple):
    x: List[int]

class Problem(NamedTuple):
    x: np.ndarray[np.int64]  # TypeError: 'type' object is not subscriptable
```

**Comment by olliethomas** [comment]
which version of python are you using? You may need 
```
from __future__ import annotations
```
as the first import in your file

**Comment by adamlichtl** [comment]
> python -V
Python 3.7.7

Confirming that "from __future__ import annotations" fixes it. Thank you!

**Comment by olliethomas** [comment]
Great - glad this helped. I'll add something to the readme for this as I'm sure other people will face this too. Thanks for reaching out 🙂
