### ISSUE TITLE
[pandas] `_AtIndexerFrame` should support indexing by [int, int]

### ISSUE THREAD

**Issue by ZeeD** [predictive-analytics-lab/data-science-types#152]
if you build a Dataframe with `header=None` the axes are `[RangeIndex(start=0, stop=4, step=1), RangeIndex(start=0, stop=9, step=1)]`, so you can't access elements with `df.at[123, 'xyz']`, but you need to use `df.at[123,456]`.

according to https://github.com/predictive-analytics-lab/data-science-types/blob/7dab8238df9e93d00be6d683d8efabbdf95fc958/pandas-stubs/core/indexing.pyi#L88, however, `_AtIndexerFrame` now only allow the second index to be a "_StrLike".

Ideally this should be a runtime check, but as I thing this is not possible with mypy, there should not be a false positive

**Comment by ZeeD** [comment]
@thomkeh Thanks for the merge

**Comment by thomkeh** [comment]
Thanks for sending a PR!
