### ISSUE TITLE
Error on merge function of pandas data frames

### ISSUE THREAD

**Issue by lrob** [predictive-analytics-lab/data-science-types#173]
Hi, 
I'm using [pyright](https://github.com/microsoft/pyright) in combination with the stubs provided by this repo. I'm getting a problem when I check the following code:

```python
import pandas as pd

d = {'a': [1, 2]}
df = pd.DataFrame(data=d)

df_merged: pd.DataFrame = df.merge(right=df)
```

By running pyright against this code I get the following errors:

```
 3:19 - error: Argument of type "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" cannot be assigned to parameter "data" of type "Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[TypeVar('_T_co')] | DataFrame | Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[TypeVar('_T_co')]] | None" in function "__init__"
  Type "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" cannot be assigned to type "Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[TypeVar('_T_co')] | DataFrame | Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[TypeVar('_T_co')]] | None"
    "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" is incompatible with "Series[TypeVar('_DType')]"
    "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" is incompatible with "Index[TypeVar('_T')]"
    "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" is incompatible with "ndarray[TypeVar('_DType')]"
    "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" is incompatible with "Sequence[TypeVar('_T_co')]"
    "Dict[_str, Series[TypeVar('_DType')] | Index[TypeVar('_T')] | ndarray[TypeVar('_DType')] | Sequence[int]]" is incompatible with "DataFrame"
    Cannot assign to "None"
      TypeVar "_VT" is invariant
... (reportGeneralTypeIssues)
  4:13 - error: "df.merge(right=df)" has type "Series[Unknown]" and is not callable (reportGeneralTypeIssues)
  4:1 - error: Type of "df_merged" is unknown (reportUnknownVariableType)
````
Ignoring error 3.19 (that however is not clear to me as well), I would like to focus on error 4:13. Why the function `merge` is said to have type  `Series[Unknown]`?

**To Reproduce**
install data-science-types stubs:
`pip install data-science-types`

install pyright:
`sudo npm install -g pyright`

run the file with the code above:
`pyright test.py`

I've already posted the [issue on pyright](https://github.com/microsoft/pyright/issues/1049) and I have been suggested to submit an issue here because pyright is behaving accordingly with the information provided by the sutbs.

**Comment by olliethomas** [comment]
Thanks for getting in touch! Yes, `df.merge` is missing right now, but there is currently a [PR which adds it](https://github.com/predictive-analytics-lab/data-science-types/pull/168)!

You might come across a few functions where either the definition is missing, or you want to use it in a slightly different way. Numpy and Pandas are massive, and we've got a long way to go before we can say we've covered enough! If you'd like to add new type signatures, please do so via a PR, it would be great to have you aboard as a contributor.
