### ISSUE TITLE
matplotlib.pyplot.close optional argument

### ISSUE THREAD

**Issue by DeltaSigma130** [predictive-analytics-lab/data-science-types#181]
matplotlib.pyplot.close has None as a default argument, however, the stub does not specify None.

https://matplotlib.org/api/_as_gen/matplotlib.pyplot.close.html#matplotlib.pyplot.close

Shouldn't line 217 in https://github.com/predictive-analytics-lab/data-science-types/blob/master/matplotlib-stubs/pyplot.pyi.in
be changed from the first to the second?

```python
def close(fig: Union[Figure, Literal["all"]]) -> None: ...
```

```python
def close(fig: Union[Figure, Literal["all"], None]) -> None: ...
```

**Comment by thomkeh** [comment]
Thanks for the report!
