### ISSUE TITLE
Pandas errors on 0.2.22

### ISSUE THREAD

**Issue by boardtc** [predictive-analytics-lab/data-science-types#222]
I am working with Anaconda3-2020.11 and did a conda install -c conda-forge data-science-types which installed
data-science-types conda-forge/noarch::data-science-types-0.2.22-pyhd8ed1ab_0

Previously I got:
error: Skipping analyzing 'pandas': found module but no type hints or library stubs

After installing data-science-types I get the new errors:
error: Name 'pd.core.frame.Series' is not defined
error: Module has no attribute "read_excel"

**Comment by thomkeh** [comment]
Yes, I'm sorry about that. This is because the type stubs are not complete. For example, in this package there is no definition of `read_excel()`. There are two possible solutions:

1. someone adds the missing type definitions to this package
2. you add `# type: ignore` at the end of the line

**Comment by boardtc** [comment]
Thanks very much for the info! I did not know about #2.
